### ISSUE TITLE
[Similarity module] Add support of scaled similarity

### ISSUE THREAD

**Issue by FanwangM** [theochem/Selector#122]
See more discussions in #73. Key points,

- [ ] Add implementation
- [ ] Add tests and docstrings

**Comment by PaulWAyers** [comment]
This is just a simple function. Given a similarity matrix, $S(i,j)$, one constructs $\frac{S(i,j)}{\sqrt{S(i,i)S(j,j)}}. For any similarity matrix, one can add a method which scales it.

**Comment by FanwangM** [comment]
I agree with the idea of getting a simple function/method for this.

**Comment by Dhrumil07** [comment]
Hi, if this issue is still not solved, I would like to solve it. Of what I understand, we need a function say `scaled_similarity_matrix()` which takes a similarity matrix as an input, and returns a scaled similarity matrix. We need to implement this in `selector.methods.similarity` and add relevant test cases.
Can someone provide clarity on this?

**Comment by FanwangM** [comment]
This remains to be solved. Thank you for offering help.
You are right about this issue and you can implement this function in https://github.com/theochem/Selector/blob/main/selector/similarity.py and write tests for it. Once the pull request is ready for review, please feel free to tag me.

In order to have a clean git history, it's a good practice to fork this repo and work on the feature branch instead of the main branch. Please feel free to let me know if you have any questions. @Dhrumil07

**Comment by Dhrumil07** [comment]
As mentioned above, the formula used to calculate scaled similarity matrix is $S(i,j)={S(i,j)\over\sqrt{S(i,i)S(j,j)}}$

Considering $S(i,j)$ denotes the similarity between $i^{th}$ sample and $j^{th}$ sample, while using Tanimoto coefficient or Modified Tanimoto coefficient to find similarity, we would always get $S(i,i)=1$ and $S(j,j)=1$ for every $(i,j)$
(as Tanimoto coefficient ranges from 0 to 1 and gives 1 when two samples being compared are the same)
Essentially, all the diagonal elements would be 1 and this will result in **scaled similarity matrix to be the same as similarity matrix**

Is this the case always? Or there are any other uses where not all diagonal elements of similarity matrices are 1 and actually there is a need to scale the similarity matrix?

**Comment by Dhrumil07** [comment]
@FanwangM I have created [pull request](https://github.com/theochem/Selector/pull/199) to solve this issue. Please can you review it.

**Comment by Dhrumil07** [comment]
Also, I have a question regarding this issue

As mentioned above, the formula used to calculate scaled similarity matrix is $S(i,j)={S(i,j)\over\sqrt{S(i,i)S(j,j)}}$

Considering $S(i,j)$ denotes the similarity between $i^{th}$ sample and $j^{th}$ sample, while using Tanimoto coefficient or Modified Tanimoto coefficient to find similarity, we would always get $S(i,i)=1$ and $S(j,j)=1$ for every $(i,j)$
(as Tanimoto coefficient ranges from 0 to 1 and gives 1 when two samples being compared are the same)
Essentially, all the diagonal elements would be 1 and this will result in **scaled similarity matrix to be the same as similarity matrix**

Is this the case always? Or there are any other uses where not all diagonal elements of similarity matrices are 1 and actually there is a need to scale the similarity matrix?

**Comment by FanwangM** [comment]
Good point. If you just look at https://github.com/theochem/Selector/blob/main/selector/similarity.py, they only give binary similarities. But we also have other similarity measurements. For example, we may have cosine similarity or any other similarity matrix provided by the user. At that point, we will need to rescale the similarity. For the case you mentioned, you can have Python log a message saying no scaling is taking effect or just print out this message.  Hope this makes things clear.  @Dhrumil07
