### ISSUE TITLE
[method.distance module]

### ISSUE THREAD

**Issue by FarnazH** [theochem/Selector#132]
To do:

- [x] Add test to reach 100% coverage
- [x] Add comments in the code
- [x] Add formulas to docstring and polish docstring (add reference).

**Comment by FanwangM** [comment]
We need to put the references under the `References` field instead of `Notes`, which remains to be done.

**Comment by FarnazH** [comment]
@maximilianvz, can you please revise the `method.dissimilarity` based classes to match the [`DirectedSphereExclusion`](https://github.com/theochem/DiverseSelector/blob/main/DiverseSelector/methods/partition.py#L47) class in terms of variable names and docstring format/wording?

**Comment by kunikachandra** [comment]
Hey @FarnazH @FanwangM when do you plan to merge the code changes so we can access the dissimilarity method? I was trying the [Getting Started](selector.qcdevs.org/starting.html) guide and couldn't use the dissimilarity method.

I am getting the error: `ModuleNotFoundError: No module named 'selector.methods.dissimilarity'`

After checking the issues and pr's related to it, I found that earlier it was present in `DiverseSelector/methods/dissimilarity.py` which no longer exists on the current main branch. 

When will it get merged? If you need any help, I am willing to contribute!
Thanks!

**Comment by FanwangM** [comment]
The `selector.methods.dissimilarity` is now renamed as `selector.methods.distance`.
