### ISSUE TITLE
GSoC 2024: Interactive web interface for `Selector`

### ISSUE THREAD

**Issue by FanwangM** [theochem/Selector#191]
## Description

Add a web interface for `Selector` with `Streamlit` and host it at https://huggingface.co/spaces.

## :books: Package Description and Impact

Selecting a representative subset out of an extensive dataset represents a vital problem for many disciplines. For example, at the final stage of virtual screening, we may have 10k candidate compounds, but it may be impractical to purchase all of them for experimental testing. Therefore, we want to select a molecule subset that covers maximized chemical space. Our package `Selector` provides a tool for people for all the subset selection tasks. 

## :construction_worker: What will you do?

This GSoC project is mainly about building a user interface to use the `Selector` package. The plan is to use `Streamlit` to build and host a web-based service on Hugging Face. 

What you will learn:
- Version control;
- How to build a web interface with `Streamlit`
- How to deploy models in Hugging Face
- Basic Usage of Docker

## :checkered_flag: Expected Outcomes

1. A web interface for medical chemists to perform subset selection
2. A docker image shared to the public for free use
3. A visualization module to interactively navigate chemical space 

| |  |
| -------- | ------- |
|Required skills | Python |
|Preferred skills | Python, Docker, Streamlit, be comfortable with math, computer science and chemistry |
|Project size | 175 hours, Medium |
| Difficulty | Medium 😉 |

## :raising_hand: Mentors

| |  | |
| -------- | ------- |------------|
|Fanwang Meng | fwmeng88_a_t_gmail_do_t_com | @FanwangM |
| Paul W. Ayers | ayers_a_t_mcmaster_do_t_ca | @PaulWAyers |

**Comment by Dhrumil07** [comment]
Hi @FanwangM and @PaulWAyers,
I am **Dhrumil Raigagla**, a final year undergrad pursuing B.Tech in Information Technology at VJTI, Mumbai. I am an open source enthusiast and want to **contribute to QC-Devs in GSoC 2024**. 
Prior to this, I have done some **internships** and have **worked on creating python modules as well as developing web-apis and web backend**.
I am **proficient in python** and have a **deep passion for maths and mathematical theories**. This skill and interest of mine aligns very well with the project.
Can you **guide me to get started and familiarized with the codebase of Selector**, by assigning some beginner-friendly tasks?
Also, I **wish to connect with you mentors and other members of the community**, so, it would be beneficial if you can provide Slack, Element, Discord or any other communication channel link.
Thank you!

**Comment by JackyZzZz** [comment]
Hi @FanwangM, @PaulWAyers, and other contributors!

I'm Jacky Xia, a third-year Computer Science student at the University of California, Irvine. 

I'm eager to learn more and contribute to the project! Could you please provide guidance on getting started with the project and suggest any initial tasks to help me integrate into the development process?

Looking forward to contributing and learning with the team.

Best,
Jacky Xia

**Comment by AdarshRawat1** [comment]
Greetings _Fanwang Meng_ and _Paul W. Ayers_ , 
I am Adarsh Rawat, currently pursuing Master’s degree in Computer Applications (MCA). 
I have experience in frontend development and deployment of machine learning models.

@JackyZzZz @Dhrumil07  Looking forward to a great collaborative experience together on this project .

**Comment by FanwangM** [comment]
Thank you for your interest in our project. @Dhrumil07 @AdarshRawat1 @JackyZzZz 

Can you please send both of us an email and your CV so we can review all the possibilities and move forward? You can include any information that you think is helpful. Thank you.

**Comment by sid1552** [comment]
Hi @FanwangM @PaulWAyers,

I am Siddharth Singh, a computer science undergraduate from India. I am very eager to contribute to the project as it aligns with my skills in front-end development. I have been fortunate enough to gain experience by working with three startups in the past.

I have already sent my resume to qcdevs@gmail.com so that we can discuss further. I am looking forward to collaborating on this project.

**Comment by anchalm03** [comment]
Hello @FanwangM @PaulWAyers !

I am **Anchal Malani**  from India. I am a fourth year student pursuing **MSc.Chemistry** and **Bachelors in Engineering** (EEE) in **BITS Goa**. Having **completed the GSoC 2023 with CalcUS-Open Chemistry**, I have experience working at the intersection of **software development** and **chemistry**. I find this project aligning with my interest, experience and skill-set. I am looking forward to contribute to **Selector (QC-Devs)**. 

I am well-versed with **Web Development**, **Version Control Systems (Git/GitHub)**, and **Docker.** My technical expertise includes **Python (Django), JavaScript, jQuery, HTML, CSS, and TypeScript.**

I would like to know what is the **best way** I can **contribute to this repository** (fix a bug /add an enhancement /add some documentation /other)?
Also, I would like to get the link to **community discussion forum** to connect with other members and work collaboratively.


Thank You!

**Comment by PaulWAyers** [comment]
@anchalm03 thanks for writing to us. We tend to engage in discussions with folks through the repository discussions. 

I'll let @FanwangM suggest a good enhancement for the repository. He is more engaged on a day-to-day basis in `Selector` than I am.

**Comment by Shashankss1205** [comment]
Warm Greetings,

I am Shashank Shekhar Singh, a second-year student at the esteemed Indian Institute of Technology **(IIT) BHU, India**. Embarking on a journey of exploration and innovation, I have immersed myself in diverse projects encompassing the realms of Web Development, Machine Learning, Deep Learning, and Computer Vision. Through these endeavors, I have cultivated a profound understanding of these cutting-edge fields, enabling me to navigate their complexities with confidence and creativity.

My proficiency extends beyond conventional boundaries, encompassing languages such as C++, Python, and TensorFlow, while also embracing emerging technologies like **Hugging Face and GPT-3.5**. This versatile skill set empowers me to handle the task in the project and My **previous experience in deploying Hugging face models using Streamlit** might speed up the entire process. 

I am eager to contribute my expertise to the GSOC'24 project. Your guidance on navigating the path to impactful contribution would be invaluable as I seek to channel my enthusiasm and skills into this endeavor.

Thank you for considering my interest in this remarkable project. I look forward to the opportunity to make a meaningful difference.

Warm regards,
Shashank Shekhar Singh

**Comment by FanwangM** [comment]
Thank you very much for your interest in our project. For the communication platform, we will use https://github.com/theochem/Selector/discussions as the workspace to discuss all the technical related topics.

**Comment by Shashankss1205** [comment]
Thank you for your prompt response !
I will do my best to get in to the orgs basics during these days.

**Comment by Harisathwik** [comment]
Hi @FanwangM @PaulWAyers 

I am Harisathwik working as Project Engineer, also pursuing **Masters in AI & ML** from **BITS Pilani** through **WILP** Programme. I am excited to express my interest in this project, as these are my go-to skills at work and for personal projects. 

I am new to open source, so your support and guidance is much appreciated. Looking forward to be a part of this journey. Thank you.

**Comment by SanjanaMahesh3** [comment]
Hi @FanwangM @PaulWAyers 
My name is Sanjana Mahesh, and I am a senior studying Computer Science Engineering with a specialization in Data Science at PES University, India. I am eager to contribute to this project as the project goals align perfectly with my skills. Could you please provide guidance on how I can get started with familiarizing myself with the project and its objectives? Any recommended resources or materials would be greatly appreciated.
Best,
Sanjana Mahesh

**Comment by FanwangM** [comment]
> Hi @FanwangM @PaulWAyers My name is Sanjana Mahesh, and I am a senior studying Computer Science Engineering with a specialization in Data Science at PES University, India. I am eager to contribute to this project as the project goals align perfectly with my skills. Could you please provide guidance on how I can get started with familiarizing myself with the project and its objectives? Any recommended resources or materials would be greatly appreciated. Best, Sanjana Mahesh

Can you please send your CV to the emails listed here? I will sending out next steps soon. Thanks.

**Comment by FanwangM** [comment]
> Hi @FanwangM @PaulWAyers
> 
> I am Harisathwik working as Project Engineer, also pursuing **Masters in AI & ML** from **BITS Pilani** through **WILP** Programme. I am excited to express my interest in this project, as these are my go-to skills at work and for personal projects.
> 
> I am new to open source, so your support and guidance is much appreciated. Looking forward to be a part of this journey. Thank you.

Can you send us your CV and any extra information that can be helpful? Thank you.

**Comment by SanjanaMahesh3** [comment]
> > Hi @FanwangM @PaulWAyers My name is Sanjana Mahesh, and I am a senior studying Computer Science Engineering with a specialization in Data Science at PES University, India. I am eager to contribute to this project as the project goals align perfectly with my skills. Could you please provide guidance on how I can get started with familiarizing myself with the project and its objectives? Any recommended resources or materials would be greatly appreciated. Best, Sanjana Mahesh
> 
> Can you please send your CV to the emails listed here? I will be sending out next steps soon. Thanks. @SanjanaMahesh3

Thanks for your reply. I have sent my CV via email.

**Comment by shawakash** [comment]
Hi  @FanwangM @PaulWAyers !
I am interested in contributing to this project
Have mailed you my cv.

Regards,
Akash

**Comment by FanwangM** [comment]
Hi @Shashankss1205. For some unknown reason, I didn't get your email and CV. Can you send it again? Thanks.

**Comment by FanwangM** [comment]
> Harisathwik

Can you send out an email with your CV to us? Thank you.

**Comment by FanwangM** [comment]
> Hi @FanwangM @PaulWAyers,
> 
> I am Siddharth Singh, a computer science undergraduate from India. I am very eager to contribute to the project as it aligns with my skills in front-end development. I have been fortunate enough to gain experience by working with three startups in the past.
> 
> I have already sent my resume to [qcdevs@gmail.com](mailto:qcdevs@gmail.com) so that we can discuss further. I am looking forward to collaborating on this project.

Can you send me an email regarding your CV and other information. Thank you.

**Comment by FanwangM** [comment]
> Greetings _Fanwang Meng_ and _Paul W. Ayers_ , I am Adarsh Rawat, currently pursuing Master’s degree in Computer Applications (MCA). I have experience in frontend development and deployment of machine learning models.
> 
> @JackyZzZz @Dhrumil07 Looking forward to a great collaborative experience together on this project .

Can you send me an email along with your CV? Thank you. @AdarshRawat1

**Comment by sid1552** [comment]
> > Hi @FanwangM @PaulWAyers,
> > I am Siddharth Singh, a computer science undergraduate from India. I am very eager to contribute to the project as it aligns with my skills in front-end development. I have been fortunate enough to gain experience by working with three startups in the past.
> > I have already sent my resume to [qcdevs@gmail.com](mailto:qcdevs@gmail.com) so that we can discuss further. I am looking forward to collaborating on this project.
> 
> Can you send me an email regarding your CV and other information. Thank you. @sid1552

Hi @PaulWAyers @FanwangM   , I have sent my cv to qcdevs@qcdevs.org . Also, I have messaged you @FanwangM  on Twitter regarding the same.

**Comment by Shashankss1205** [comment]
> Hi @Shashankss1205. For some unknown reason, I didn't get your email and CV. Can you send it again? Thanks.

Hi @FanwangM , I have sent my CV to [qcdevs@qcdevs.org](mailto:qcdevs@qcdevs.org), please confirm if you have got the same. Sorry for the delay.
Thank You
Shashank Shekhar Singh

**Comment by Harisathwik** [comment]
Hi @FanwangM , I have sent my profile to your email. Sorry for the delay

**Comment by Harisathwik** [comment]
> > Hi @FanwangM @PaulWAyers
> 
> > I am Harisathwik working as Project Engineer, also pursuing Masters in AI & ML from BITS Pilani through WILP Programme. I am excited to express my interest in this project, as these are my go-to skills at work and for personal projects.
> 
> > I am new to open source, so your support and guidance is much appreciated. Looking forward to be a part of this journey. Thank you.
> 
> Can you send out an email with your CV to us? Thank you. @Harisathwik

Hi @FanwangM , I have sent my profile to your email. Sorry for the delay

**Comment by kunikachandra** [comment]
Hi @FanwangM , I have sent my CV to you and @PaulWAyers via email.
