### ISSUE TITLE
Update in Docs/Code necessary

### ISSUE THREAD

**Issue by Shashankss1205** [theochem/Selector#194]
Hello Developers,
I wanted to mention that the doc has been outdated at some instances with respect to the code : 
![Screenshot (221)](https://github.com/theochem/Selector/assets/123410790/a55d1e06-d205-486c-bde1-07b6589e7531)
In the above image about Running Dissimilarity Algorithms, 
`from selector.methods.dissimilarity import *` should be changed to `from selector.methods.distance import *` because in a previous commit, the name of the dissimilarity module has been changed to distance.
Similarly, `selected_ids1 = selector.select(arr=arr_dist, size=12)` should be changed to `selected_ids1 = selector.select(X=arr_dist, size=12)` as evident from the image 
![Screenshot (220)](https://github.com/theochem/Selector/assets/123410790/385acbbb-6bdb-4fbe-9ce8-5805ef0fb3c8)

Kindly look into all such changes or guide me so that I can make the meaningful changes in the doc or the code to make them both compatible.
The following 2 images demonstrate how the changes I made:
![Screenshot (222)](https://github.com/theochem/Selector/assets/123410790/140e164a-6c42-4856-8ffb-b56fbaeb5b7f)
![Screenshot (223)](https://github.com/theochem/Selector/assets/123410790/58f18a8f-9230-440e-b406-eb5bf9135228)
![Screenshot (223)](https://github.com/theochem/Selector/assets/123410790/0296cd02-8e68-4ec4-98d2-f09741ceed9e)
![Screenshot (222)](https://github.com/theochem/Selector/assets/123410790/3bd76bdd-edf9-4e07-8335-2e6f1ec93369)

**Comment by Shashankss1205** [comment]
Sorry for duplicated images at the bottom.
And this is a screenshot of the renaming of the file from dissimilarity to distance:
![image](https://github.com/theochem/Selector/assets/123410790/2383222b-027d-47e0-b4b4-127ec3c5abe0)

**Comment by Shashankss1205** [comment]
Kindly reach back to me once you take a look at the problem so that I can provide my help as well.
Thank you !

**Comment by Shashankss1205** [comment]
Hello @FanwangM , @FarnazH 
Are there any updates regarding this issue? 
Thank You!

**Comment by Shashankss1205** [comment]
Hello @FanwangM & @FarnazH 
Have you looked at the issue?
Thank You!

**Comment by FanwangM** [comment]
Sorry for the delay. We use the Jupyter Book to host the documentation with sources from the Jupyter notebooks. The problem you mentioned is being fixing in https://github.com/theochem/Selector/pull/186. I would suggest wait for https://github.com/theochem/Selector/pull/186 to be merged and see how should further polish the documentation. But thanks for offering the help.

**Comment by FanwangM** [comment]
I am going to close this issue for now, but please feel free to reopen it when needed.

**Comment by Shashankss1205** [comment]
> Sorry for the delay. We use the Jupyter Book to host the documentation with sources from the Jupyter notebooks. The problem you mentioned is being fixing in #186. I would suggest wait for #186 to be merged and see how should further polish the documentation. But thanks for offering the help. @Shashankss1205

Okay, Thanks @FanwangM , Now I got to know Why was I feeling outdated in those Starting stuffs.

I am hoping that I can provide with any help related to this project as it excites me the most amongst all Projects.
Also I would like to know are there any tests or procedures that I should follow so as to pave my way a bit closer towards being a contributor at the Organization.

**Comment by FanwangM** [comment]
I'm not sure if I fully understand your comments. Are you referring to coding practices? If so, we have set up GitHub Actions to automatically run tests, https://github.com/theochem/Selector/tree/main/.github/workflows. 

We will post more updates later this week regarding this GSoC project.

**Comment by Shashankss1205** [comment]
Okay I understand.
Thank You.
