### ISSUE TITLE
Inconsistent results of `Medoid` running on MacOS and Ubuntu

### ISSUE THREAD

**Issue by FanwangM** [theochem/Selector#238]
A weird behavior was observed for running `Medoid` method for selecting subsets from a chemical library. Here is the code block to reproduce it,

```python
import numpy as np
import scipy
from selector.methods.partition import Medoid

# load features
ecfp = np.loadtxt("ecfp.txt")
# load class labels
class_labels = np.loadtxt("class_labels.txt")

# perform subset selection
picker = Medoid(
    func_distance=lambda x, y: scipy.spatial.minkowski_distance(x, y) ** 2,
    ref_index=0,
    scaling=10,
)
selected_indices = picker.select(
    ecfp,
    420,
    class_labels,
)

print(selected_indices)

# save selected_indices to txt file
# np.savetxt("ecfp_selected.txt", np.array(selected_indices), delimiter=",", fmt='%s')
```

The selected indices got from MacOS was named as [ecfp_selected_Mac.txt](https://github.com/user-attachments/files/16488982/ecfp_selected_Mac.txt), while the one got from Linux is named as 
[ecfp_selected_Ubuntu.txt](https://github.com/user-attachments/files/16488984/ecfp_selected_Ubuntu.txt)

After examining the data, it is noticed that there are some identical features, but different molecules. I have tried to update the sorting step with numpy in [8648e16](https://github.com/theochem/Selector/pull/235/commits/8648e1669ff2a2276d197bd58c9a1dc61af6edc8), but it didn't help. https://github.com/theochem/Selector/pull/235 demonstrates these efforts where testing can pass for Ubuntu images while failing for MacOS images, https://github.com/theochem/Selector/actions/runs/10239497466.

[ecfp.txt](https://github.com/user-attachments/files/16488994/ecfp.txt)
[class_labels.txt](https://github.com/user-attachments/files/16488997/class_labels.txt)

Can you please help take a look at this? Thank you very much. @marco-2023

**Comment by marco-2023** [comment]
@FanwangM I am having problems running the code. I am not able to run it in the main branch. it gives:

![image](https://github.com/user-attachments/assets/68e24d3a-7a4a-4602-8e3c-bf306def8e86)

Is there anything I am missing? Should I work on another branch?

**Comment by FanwangM** [comment]
Sorry for the confusion. You will need to hack the code to make it work, 

```
        # elim_candidates can be integer or array of integers
        # https://github.com/scipy/scipy/blob/a2a287d1f7c81154256ba742b4b8bb108a612166/scipy/spatial/_kdtree.py#L476
        if isinstance(elim_candidates, np.intp):
            elim_candidates = [elim_candidates]
```
which can be found at https://github.com/theochem/Selector/pull/235/files. More details are explained in https://github.com/theochem/Selector/issues/236.

**Comment by FanwangM** [comment]
As @msricher pointed out that this is a known issue with `scipy` implementation of KD-Tree, https://github.com/scipy/scipy/issues/19029.

**Comment by marco-2023** [comment]
@FanwangM  As a way to keep track of when and why the issue occurs we can check the selected index at each iteration and the corresponding distance value, add a print at line 651 of `partition.py`

```python 
                )
            print(f"Selected {new_point.index} with distance {new_point.distance}")
            count += 1
        return selected
```
I have the corresponding log for Linux, we need the MacOS one.
I don't think we will be able to attain perfect  reproducibility, but at least we should be able to understand the impact of the changes.

**Comment by FanwangM** [comment]
Here is the log from MacOS. @marco-2023 
[MacOS_debugging_log.txt](https://github.com/user-attachments/files/16532386/MacOS_debugging_log.txt)

I agree that it's OK not to have perfect reproducibility, but we should make the users aware of this and at least document this in the docstrings.

**Comment by marco-2023** [comment]
@FanwangM Here is a small partial comparison of the selected indices:
```
Selected 32 with distance 8.000000000000002            Selected 32 with distance 8.000000000000002
Selected 58 with distance 5.999999999999999            Selected 58 with distance 5.999999999999999
Selected 68 with distance 4.0                          Selected 68 with distance 4.0
Selected 57 with distance 4.25                         Selected 57 with distance 4.25
Selected 36 with distance 3.5200000000000005           Selected 36 with distance 3.5200000000000005
Selected 24 with distance 3.111111111111112            Selected 24 with distance 3.111111111111112
Selected 62 with distance 3.285714285714285            Selected 62 with distance 3.285714285714285
Selected 56 with distance 2.765625                     Selected 67 with distance 2.765625
Selected 19 with distance 3.0740740740740744           Selected 56 with distance 3.0740740740740744
Selected 5 with distance 2.6900000000000004            Selected 19 with distance 3.0900000000000003
```
Left are macOS results right are Linux results. If you see line 8 (selected 56 on the left), the distance (used as a measure to select the point) is the same for 67 on the Linux side. I guess that this problem will happen when there are several trees with the same distance value. As we only select one, the one selected will be the first to be evaluated. From this point onward, the sets diverge. 

We can explain this.

**Comment by FanwangM** [comment]
Given that we have identified the problem, we are going to close this issue. More explanations will be given in the docstrings.

**Comment by FanwangM** [comment]
Test added in https://github.com/theochem/Selector/pull/235.
