### ISSUE TITLE
Broken Tutorial Notebook Links

### ISSUE THREAD

**Issue by FarnazH** [theochem/Selector#268]
Considering the recent module renamings, the links in the tutorial notebooks no longer work. I have included an example below.

<img width="1238" alt="Screenshot 2024-09-20 at 8 36 48 PM" src="https://github.com/user-attachments/assets/383a6cd3-634e-4589-bd89-5ec3c85231d8">

@andruizd, can you please check and fix all the tutorial notebook links? Thanks.

**Comment by FanwangM** [comment]
This has been fixed in https://github.com/theochem/Selector/pull/271. So I am going to close this for now.
