### ISSUE TITLE
[Website] Host documentation with gh-pages or our own domain

### ISSUE THREAD

**Issue by FanwangM** [theochem/Selector#47]
Generate the documentation and host it with our own domain.

**Comment by PaulWAyers** [comment]
I've also reserved `selector.qcdevs.org`

**Comment by FarnazH** [comment]
@RichRick1 and @FanwangM, I have looked at the website, and it looks good overall. Can you please make sure the sections on the landing page as well as the table of contents (on the left) are as similar as possible to iodata, procrustes, and other packages we have published? Thanks.

**Comment by PaulWAyers** [comment]
We talked about a logo, I can't remember whether it was with Rick or Fanwang. I think it had something to do with "selecting" letters out of the word "selector".....

**Comment by FanwangM** [comment]
Probably it's Rick's idea. Do you mean something like this? @PaulWAyers 

<img width="747" alt="image" src="https://github.com/theochem/DiverseSelector/assets/22950235/a8a60e9f-b82d-4c85-845e-fd123252d78e">

**Comment by PaulWAyers** [comment]
It was more like ripping letters out of the word....let's see what @RichRick1 says.

**Comment by RichRick1** [comment]
@PaulWAyers @FanwangM I'm working on it. Should send you in a coming days the prototype

**Comment by RichRick1** [comment]
@PaulWAyers @FanwangM does this work?
![telegram-cloud-photo-size-2-5291748116875300440-y](https://github.com/theochem/DiverseSelector/assets/36164007/d174943d-e958-4060-b43b-1b27bf7b16c6)

**Comment by FanwangM** [comment]
I love it. Do you have a PSD or other vector format file that you can share? @RichRick1

**Comment by RichRick1** [comment]
@FanwangM Yes, let me email it to you

**Comment by PaulWAyers** [comment]
I think it was @Ali-Tehrani who also had an idea on the logo. Before we go too far good to see what he'd sketched. 

With a tiny bit of work (e.g., probably shortening to "Select" and stretching vertically) one has a nice favicon too.

**Comment by PaulWAyers** [comment]
I'm so confused about this....someone showed me something once.

Anyway, I think we go with @RichRick1 's logo idea for now.

**Comment by FanwangM** [comment]
Given we have our website running now and I am going to close this issue. Thanks for everyone's help on this!
