### ISSUE TITLE
[Diversity module] Problem of using `shannon_entropy` for computing diversity

### ISSUE THREAD

**Issue by FanwangM** [theochem/Selector#67]
Sometimes, this function can return us an invalid value, NaN. You can reproduce the error by running the notebook as attached with the latest code in this repo. I think the main problem is we may have zeros in the denominator.

[diversity_problem.zip](https://github.com/theochem/DiverseSelector/files/8683934/diversity_problem.zip)

Can you fix this? Thank you. 
@Khaleeh

**Comment by FanwangM** [comment]
Shannon entropy (SE) should follow [Shannon Entropy-Based Fingerprint Similarity Search Strategy, _J. Chem. Inf. Model._ **2009**, 49, 1687–1691](https://doi.org/10.1021/ci900159f). The equation is

![image](https://user-images.githubusercontent.com/22950235/189797373-11d52c44-b3c4-440c-afdb-6513923b5a65.png)

**Comment by FanwangM** [comment]
We should check if this is still a problem. If so, we will need to fix the bug.

**Comment by PaulWAyers** [comment]
Write a test to check this. It's a relatively straightforward task, consisting of converting the notebook that shows the issue into a test.

**Comment by FanwangM** [comment]
This is addressed in https://github.com/theochem/Selector/pull/177.
