### ISSUE TITLE
[Docs] List the application scenarios of `Selector`

### ISSUE THREAD

**Issue by FanwangM** [theochem/Selector#70]
It would be beneficial for people to know how they can use our package for practical problems and I think we can make a list for people in the manuscript.

- subset selection for HTS/virtual screening/machine learning
- validation dataset hold-out (stratified version)

**Comment by PaulWAyers** [comment]
This supersedes #48

**Comment by FanwangM** [comment]
We have covered this part in our manuscript and I will close this issue.
